import type { ActiveTrip } from '@/shared/types'

export const TEST_TRIP: ActiveTrip = {
  created_at: '2021-04-09T06:00:00.000Z',
  setup: {
    current_location: 'Richmond, VA',
    pickup: 'Richmond, VA',
    destination: 'Springfield, MA',
    cycle_hours_used: 0,
  },
  locations: {
    current: { lat: 37.5407, lng: -77.4360, display_name: 'Richmond, VA', city: 'Richmond', state: 'VA' },
    pickup:  { lat: 37.5407, lng: -77.4360, display_name: 'Richmond, VA', city: 'Richmond', state: 'VA' },
    destination: { lat: 42.1015, lng: -72.5898, display_name: 'Springfield, MA', city: 'Springfield', state: 'MA' },
  },
  route: {
    total_miles: 748,
    total_duration_hrs: 11.5,
    geometry: {
      type: 'LineString',
      coordinates: [
        [-77.4360, 37.5407],
        [-77.4608, 38.3032],
        [-76.9856, 38.8951],
        [-75.5474, 39.7447],
        [-75.1652, 39.9526],
        [-74.7429, 40.2171],
        [-74.1724, 40.6628],
        [-73.9442, 40.6782],
        [-72.9279, 41.3083],
        [-72.5898, 42.1015],
      ],
    },
    legs: [
      { miles: 374, duration_hrs: 5.8 },
      { miles: 374, duration_hrs: 5.7 },
    ],
  },
  current_day: 2,
  days: [
    {
      day_number: 1,
      date: '2021-04-09',
      driver_name: 'John E. Doe',
      driver_number: 'D-1041',
      co_driver: 'N/A',
      carrier_name: "John Doe's Transportation",
      home_terminal: 'Washington, D.C.',
      tractor: '123',
      trailer: '20544',
      shipper: "Don's Paper Co.",
      commodity: 'Paper products',
      load_number: 'ST13241564',
      total_miles: 350,
      entries: [
        { time: '00:00', status: 'OFF_DUTY',           location: 'Richmond, VA',       remarks: '',                bracket: false },
        { time: '06:00', status: 'ON_DUTY_NOT_DRIVING', location: 'Richmond, VA',       remarks: 'Pre-trip / TIV', bracket: false },
        { time: '06:30', status: 'DRIVING',             location: 'Richmond, VA',       remarks: '',                bracket: false },
        { time: '08:00', status: 'ON_DUTY_NOT_DRIVING', location: 'Fredericksburg, VA', remarks: 'Scale',           bracket: false },
        { time: '08:30', status: 'DRIVING',             location: 'Fredericksburg, VA', remarks: '',                bracket: false },
        { time: '11:30', status: 'OFF_DUTY',            location: 'Baltimore, MD',      remarks: '30 min break',    bracket: true  },
        { time: '12:00', status: 'DRIVING',             location: 'Baltimore, MD',      remarks: '',                bracket: false },
        { time: '13:00', status: 'ON_DUTY_NOT_DRIVING', location: 'Philadelphia, PA',   remarks: 'Fuel stop',       bracket: false },
        { time: '14:00', status: 'DRIVING',             location: 'Philadelphia, PA',   remarks: '',                bracket: false },
        { time: '16:00', status: 'SLEEPER_BERTH',       location: 'Cherry Hill, NJ',    remarks: 'Post-trip / TIV', bracket: false },
        { time: '17:00', status: 'DRIVING',             location: 'Cherry Hill, NJ',    remarks: '',                bracket: false },
        { time: '18:00', status: 'ON_DUTY_NOT_DRIVING', location: 'Newark, NJ',         remarks: '',                bracket: false },
        { time: '19:00', status: 'OFF_DUTY',            location: 'Newark, NJ',         remarks: '10 hour break',   bracket: false },
      ],
      post_trip: { defects: 'none' },
      completed: true,
    },
    {
      day_number: 2,
      date: '2021-04-10',
      driver_name: 'John E. Doe',
      driver_number: 'D-1041',
      co_driver: 'N/A',
      carrier_name: "John Doe's Transportation",
      home_terminal: 'Washington, D.C.',
      tractor: '123',
      trailer: '20544',
      shipper: "Don's Paper Co.",
      commodity: 'Paper products',
      load_number: 'ST13241564',
      total_miles: 398,
      entries: [
        { time: '00:00', status: 'OFF_DUTY',            location: 'Newark, NJ',       remarks: '',                  bracket: false },
        { time: '05:00', status: 'ON_DUTY_NOT_DRIVING', location: 'Newark, NJ',       remarks: 'Pre-trip',          bracket: false },
        { time: '05:30', status: 'DRIVING',             location: 'Newark, NJ',       remarks: '',                  bracket: false },
        { time: '08:00', status: 'ON_DUTY_NOT_DRIVING', location: 'New York, NY',     remarks: 'Delivery stop',     bracket: false },
        { time: '09:00', status: 'DRIVING',             location: 'New York, NY',     remarks: '',                  bracket: false },
        { time: '12:00', status: 'OFF_DUTY',            location: 'Hartford, CT',     remarks: 'Lunch break',       bracket: true  },
        { time: '12:30', status: 'DRIVING',             location: 'Hartford, CT',     remarks: '',                  bracket: false },
        { time: '15:00', status: 'ON_DUTY_NOT_DRIVING', location: 'Springfield, MA',  remarks: 'Final delivery',    bracket: false },
        { time: '16:00', status: 'OFF_DUTY',            location: 'Springfield, MA',  remarks: '',                  bracket: false },
      ],
      post_trip: { defects: 'none' },
      completed: true,
    },
  ],
}
